accounts/urls.py
from django.urls import path
from accounts import views as account_view
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/', account_view.register, name='register'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('profile/', account_view.profile, name='profile'),
    path('change_profile/', account_view.change_profile, name='change_profile'),

]

blog/urls.py
from django.urls import path

from blog.views import home, add_student, update_student, delete_student

urlpatterns = [
    path('', home, name='home'),
    path('add-student/', add_student, name='add_student'),
    path('update-student/<int:student_id>/', update_student, name='update_student'),
    path('delete-student/<int:student_id>/', delete_student, name='delete_student')
]

config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('accounts.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=20, unique=True)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['username', 'email']

    def __str__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='account_img/', blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s image"

blog/models/blog.py
from django.db import models

from accounts.models import CustomUser


class Blog(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/models/students.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Student(models.Model):
    GENDER_CHOICE = {
        "MN": 'Erkak',
        'WN': 'Ayol',
        'OT': 'Boshqa'
    }
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, null=True)
    birthday = models.DateField(null=True)
    phone = models.CharField(max_length=12)
    payed = models.BooleanField(default=False)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICE, default='MN')
    image = models.ImageField(upload_to='student/', null=True, blank=True)
    total_points = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    passed_points = models.IntegerField(default=60, validators=[MinValueValidator(0), MaxValueValidator(100)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"({self.id} {self.first_name!r} ball={self.total_points!r})"

    @property
    def fullname(self):
        return f"{self.first_name} {self.last_name}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from accounts.models import CustomUser, Profile


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'phone', 'email']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['phone', 'username', 'email', 'first_name', 'last_name']


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image', )

blog/forms/students.py
from django import forms

from blog.models.students import Student


class UserCreationForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'gender', 'image', 'phone', 'total_points', 'birthday', 'payed']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
        }

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from accounts.forms import CustomUserCreationForm, CustomUserChangeForm, ProfileChangeForm
from accounts.models import CustomUser, Profile


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, F"{user.username} foydalanuvchi muvaffaqiyatli ro'yxatdan o'tdi!")
            return redirect('accounts:login')
    else:
        messages.warning(request, F"Biz hozirda test rejimida ishlayapmiz!")
        form = CustomUserCreationForm()
    context = {
        "form": form
    }
    return render(request, 'accounts/register.html', context=context)


def profile(request):
    return render(request, 'accounts/profile.html')


def change_profile(request):
    profile = Profile.objects.filter(user=request.user)

    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()

        if profile:
            profile = ProfileChangeForm(request.POST, request.FILES, instance=request.user.profile)
        else:
            profile = ProfileChangeForm(request.POST, request.FILES)

        if profile.is_valid():
            profile = profile.save(commit=False)
            profile.user = request.user
            profile.save()

        return redirect('accounts:profile')

    else:
        form = CustomUserChangeForm(instance=request.user)
        if profile:
            profile = ProfileChangeForm(instance=request.user.profile)
        else:
            profile = ProfileChangeForm()

    context = {
        "form": form,
        "profile": profile
    }
    return render(request, 'accounts/profile_change.html', context=context)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from blog.forms.students import UserCreationForm
from blog.models.students import Student


@login_required
def home(request):
    student = Student.objects.all()
    search_student = request.GET.get('search_q')  # AL
    if search_student:
        student = Student.objects.filter(
            Q(first_name__icontains=search_student) | Q(last_name__icontains=search_student) | Q(
                phone__icontains=search_student))

    context = {
        "students": student
    }
    return render(request, 'blog/students.html', context=context)


@login_required
def add_student(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'blog/add_student.html', {'form': form})


@login_required
def update_student(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    if request.method == 'POST':
        form = UserCreationForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = UserCreationForm(instance=student)
    context = {'form': form, 'student': student}
    return render(request, 'blog/update_student.html', context=context)


@login_required
def delete_student(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    if request.method == 'POST':
        student.delete()
        return redirect('home')
    return render(request, 'blog/delete_student.html', {'student': student})

templates/accounts/account_base.html
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}

    {% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body class="h-100">
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show sticky-top" role="alert">
        <strong>{{ message.tags|upper }}: </strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}

<div class="container mt-2">
    {% block content %}

    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

templates/accounts/login.html
{% extends 'accounts/account_base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <p class="h3">Login</p>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Login</button>
                <p class="mt-2">or create account <a href="{% url 'accounts:register' %}">Register</a>?</p>
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/logout.html
{% extends 'accounts/account_base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Logout
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <p class="h3 text-primary">Logged Succesfully</p>
        </div>
        <div class="card-body">
            <p class="h4">Qayta login qilish uchun <a href="{% url 'accounts:login' %}">Login</a> ni bosing!</p>
        </div>
    </div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
    Profile
{% endblock %}

{% block content %}
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">{{ user.get_full_name }}</h2>

            <p class="lead">{{ user.phone }}</p>
            <p class="lead">{{ user.email }}</p>
            <p class="lead">{{ user.username }}</p>
            <a href="{% url 'accounts:change_profile' %}" class="btn btn-outline-success">Change my profile</a>
        </div>
        <div class="col-md-5">
            {% if user.profile.image %}
                <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500"
                     src="{{ user.profile.image.url }}"
                     data-holder-rendered="true" style="width: 500px; height: 500px; object-fit: cover">
            {% else %}
                <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500"
                     src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22500%22%20height%3D%22500%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20500%20500%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_197c76cfd4c%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A25pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_197c76cfd4c%22%3E%3Crect%20width%3D%22500%22%20height%3D%22500%22%20fill%3D%22%23EEEEEE%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22185.109375%22%20y%3D%22261.1796875%22%3E500x500%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                     data-holder-rendered="true" style="width: 500px; height: 500px;">
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/accounts/profile_change.html
{% extends 'accounts/account_base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <p class="h3">Profile Change</p>
        </div>
        <div class="card-body">
            <form method="POST" action="{% url 'accounts:change_profile' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                {{ profile|crispy }}
                <button type="submit" class="btn btn-primary">Change</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'accounts/account_base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Register
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <p class="h3 text-primary">Register</p>
        </div>
        <div class="card-body">
            <form action="{% url 'accounts:register' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="Submit" class="btn btn-primary">Register</button>
            </form>
            <p class="mt-2">or login account <a href="{% url 'accounts:login' %}">Login</a> ? </p>
        </div>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form method="GET" action="{% url 'home' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="search_q" type="search" placeholder="Search Students"
                   aria-label="Search" required>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">{{ user.username|capfirst }} Profile</a>
                </li>
                <form method="POST" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                    <button class="btn btn-outline-danger">Logout</button>
                </form>
            </ul>
        {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>


<div class="container my-2">
    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<script>
    function previewImage(event) {
        const [file] = event.target.files;
        if (file) {
            const preview = document.getElementById("preview");
            preview.src = URL.createObjectURL(file);
            preview.style.display = "block";

            // Eski rasmni yashirish
            const currentImage = document.getElementById("current-image");
            if (currentImage) {
                currentImage.style.display = "none";
            }
        }
    }

</script>
</body>
</html>

templates/blog/add_student.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<a href="{% url 'home' %}">Students List</a>

<div class="card mt-5">

    <div class="card-header">
        <h3 class="text-success">Save new student</h3>
    </div>

    <div class="card-body">
        <blockquote class="blockquote mb-0">

            <form method="POST" action="{% url 'add_student' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Save</button>
            </form>

        </blockquote>
    </div>
</div>

{% endblock %}

templates/blog/blog.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ziyo</title>
</head>
<body>

    <h1>Ziyo maskani</h1>

    <h3>1-masala</h3>
    <p>{{ shart }}</p>
    <p>Natija: {{ a }} + {{ b }} = {{ c }}</p>
    <p>{{ date_time }}</p>

    <h3>Talabalar ro'yxati:</h3>
    <ol>
        {% for student in students %}
            <li>
                {% if student.payed %}
                ✅
                {% else %}
                ❌
                {% endif %}

                {{ student.first_name }}  {{ student.last_name }}
            </li>
        {% endfor %}
    </ol>


    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Yangi_Oʻzbekiston_-_Yoshlar_Ziyo_Maskani.jpg/1200px-Yangi_Oʻzbekiston_-_Yoshlar_Ziyo_Maskani.jpg" alt="rasm">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci molestiae repellendus rerum unde voluptate.
        Aspernatur distinctio earum ex id modi non officia omnis perspiciatis quam, repudiandae saepe, temporibus vel
        veniam?
    </p>

</body>
</html>

templates/blog/delete_student.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <div class="card mt-5">

        <div class="card-header">
            <h3><span class="text-danger">Delete</span> {{ student.fullname }}</h3>
        </div>

        <div class="card-body">
            <blockquote class="blockquote mb-0">

                <form method="POST" action="{% url 'delete_student' student.id %}">
                    {% csrf_token %}
                    {% if student.image %}
                        <img src="{{ student.image.url }}" alt="rasm" style="width: 100px;">
                    {% else %}
                        <img src="#" alt="Rasm mavjud emas!">
                        <p>Rasm mavjud emas!</p>
                    {% endif %}

                    <p>Ism: {{ student.first_name }}</p>
                    <p>Familya: {{ student.last_name }}</p>
                    <p>Tel: {{ student.phone }}</p>
                    <p>Gender: {{ student.gender }}</p>
                    <p>Payed: {{ student.payed|yesno:'✅,❌' }}</p>
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <a class="btn btn-secondary" href="{% url 'home' %}">Cancel</a>
                </form>
            </blockquote>
        </div>

    </div>

{% endblock %}

templates/blog/students.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'add_student' %}"> Add Student</a>
<table class="table mt-5">
    <thead class="thead-dark">
    <tr>
        <th scope="col">№</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Gender</th>
        <th scope="col">Phone</th>
        <th scope="col">Birthday</th>
        <th scope="col">Payed</th>
        <th scope="col" class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
    {% for student in students %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ student.first_name}}</td>
        <td>{{ student.last_name}}</td>
        <td>{{ student.gender}}</td>
        <td>{{ student.phone}}</td>
        <td>{{ student.birthday }}</td>
        <td> {{ student.payed|yesno:"✅,❌" }}</td>

        <td>
            <a href="{% url 'update_student' student.id %}">Update</a>
            <a href="{% url 'delete_student' student.id %}">Delete</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/blog/update_student.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<a href="{% url 'home' %}">Students List</a>

<div class="card mt-5">

    <div class="card-header">
        <h3><span class="text-primary">Update</span> {{ student.fullname }}</h3>
    </div>

    <div class="card-body">
        <blockquote class="blockquote mb-0">

            <form method="POST" action="{% url 'update_student' student.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </blockquote>
    </div>

</div>

{% endblock %}